travis:
  secure:
    BINSTAR_TOKEN: Ne/i0a1hIIMZTN0F6sGHo4Lez7nSjzI0NCpGjwkIjmk5tjWTkvGfjKtScApeACOo8QA15w2P1hPYx8KwhZczQ/0Gv1suPfndVF+uJO0Forid1P71CYfWQCTM5wBQ4P72I9me1woV5CdboRyyWzeH1rMGu7rVXqS0x0MhOu3mwbTD1Vw4rFxyGwzXMHM17WGDkIZVV9jQmV9WkEac4ErbNrMOSqv5jF68br1+8Z2HXYQxte/ZPAAkon8BQ/+3AL6bkb4t4yjfu16RH0/8UR6bbHXyfyq9sLYXNS2VhHQr/pX36rrL5HkPWBu0F/U+BWKCz3G5aFGBsRL++dUJTdrPP1uACg+zkNtJXvGlfpCJnM00mzIganGks0N0GXh/qyDrJeTYmLRCHG4S7nXBDE5rMG9lLCNSKQtaUc7WiB/VHuLgVzMkYoCczGZf8rKnAGJfig4Nmqyo3xgq1gk6yo2YFKhAQWsKx9RstfiWPlLGi/sus7e0hO3Lujzb+a3a6K15RENmTVCAfiC3M3BE1dS/60eNC0FqoHg0mMGwQRY0XryCX0uJakymVl717dGyQcUUV4DaACqNJqRjG5vzReH7qjPrKoTeEsJBqHJROJ7opMqT4F+a2lcH+JOS+DSR+Xpck14BhowAQiIlLbC5oG1n9qvPA00bz6qVBZYQ/5LlTdQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
