travis:
  secure:
    BINSTAR_TOKEN: tlE1noNGLG7a0+X7Pyuton+YjhlNG0ygoAJeXYUxNuoONlHCc9+9Nmn+xJFv2GF0f0z3cApSbsTbp+s/catmHul0QpV8zwwwgU3hI0R+/iKtTDAjjnzYSQUxdKUKbyfKBgWC8AoRIZYMXI+P4PIHoQeUgFZ3YEJroyl+60+ahkd5aklls4KyZwv6mX7ahDDNKf4MSJimDxJGjwY0WJLp1cjoBa/Cjuz/e39TGaHRIf8qc9SqHKGI64QWuxv1ATQvL1WEyoGO1SL4aKhYPOFANcrPTqW1JTCUPtyt+Ff/QYA67lOfpujv4bL7zDCY4WR8yoEMOs/xf1YocJ6RpgO2yDnOMP/S90K5f/ko69SS/UvawDDZHbpqN4nR2WSxhm4o1tQ8GTAYKzyAvn3xVS3U6IL9sXk3P7z6wHn78+Nal4wFOkEE780gfpvKDZyW0E549NdJAYAPPU2fdNjN1leQ39tDq5Ejo2Wltbczb2v071BPFgeHnCmT5jQmA4A12nyRYs2SEyEEHijQ0/9VP48++gYRiGxFFoqzN0VvGGHyLJW1W2X07M8kpMCtACwJNtFxHzuEXQknsWtZQFsl1UdyLYTZQypnqOpVV7mvzJAkq4aInB4YYVzlHIxrYfj/rSjHQ3opEoKdFSJhynB2kFy7siF+s+Kj7V0auTiXwps8mIo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
